// <auto-generated />
namespace _3MA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Product_AddToCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_AddToCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201709112358534_Product_AddToCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
