// <auto-generated />
namespace _3MA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Suite_and_Plan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Suite_and_Plan));
        
        string IMigrationMetadata.Id
        {
            get { return "201705191701427_User_Suite_and_Plan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
