// <auto-generated />
namespace _3MA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class POrder_Billing_Info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(POrder_Billing_Info));
        
        string IMigrationMetadata.Id
        {
            get { return "201707252029234_POrder_Billing_Info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
