// <auto-generated />
namespace _3MA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_package_and_product_objects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_package_and_product_objects));
        
        string IMigrationMetadata.Id
        {
            get { return "201705161840268_new_package_and_product_objects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
