// <auto-generated />
namespace _3MA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Product_remove_URL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_remove_URL));
        
        string IMigrationMetadata.Id
        {
            get { return "201705291928365_Product_remove_URL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
