// <auto-generated />
namespace _3MA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class POrder_fix_all_fields_POrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(POrder_fix_all_fields_POrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211854434_POrder_fix_all_fields_POrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
